### PR TITLE
Add passkey keyword to `after_passkey_authentication`

### LINKED ISSUE #14: Add `passkey` keyword parameter to `PasskeyAuthenticatable.after_passkey_authentication`
To make the callback more useful, it should include the passkey that was used to authenticate.

This would make it easier to perform actions like:
- Notifying the user that a new authentication occurred (and which passkey was used)
- Updating some app-specific data related to the passkey

So the new method signature should be:

```ruby
def after_passkey_authentication(passkey:)
...
end
```

### PR DESCRIPTION
**Pull request by Vagab**
resolves #14

### CODE REVIEW

**Comment by Vagab** [comment]
@tcannonfodder let me know if I should add any tests

**Comment by tcannonfodder** [comment]
Yep, we definitely need tests for this 💪

**Comment by tcannonfodder** [comment]
I...actually don't know if we're using those checks 😅. I need to dig into the tests. It's one of the places where devise gets gnarly because of how it's designed

**Comment by tcannonfodder** [comment]
Okay, it looks like that code is vestigial, from a previous implementation attempt. We should remove it in a subsequent PR

**Comment by tcannonfodder** [comment]
Waiting on CI to pass, but looks good! 💪

**Review by tcannonfodder — APPROVED** [review]

**Comment by tcannonfodder** [comment]
Ack, @Vagab can you rebase the latest `main` into this so that we can get CI to pass?

**Pull request merged**
